#ifndef CONFIG_H
#define CONFIG_H

// Firebase configuration
#define FIREBASE_PROJECT_ID   "argus360-c0496"
#define FIREBASE_API_KEY      "AIzaSyBtGpOwNCicAIl5FUh07nXb39Dh-XPdabE"
#define FIREBASE_DB_URL       "https://argus360-c0496-default-rtdb.europe-west1.firebasedatabase.app"

// Device details (to be replaced with specific station credentials during provisioning)
#define DEFAULT_STATION_ID    "STATION_001"
// Custom provisioning token generated by the server. 
// Devices use this on first boot to establish credentials.
#define DEFAULT_CUSTOM_TOKEN  "PLACE_PROVISIONING_TOKEN_HERE"

// Cellular settings
#define CELLULAR_APN          "a1.net" // A1 Telekom Austria SIM APN
#define CELLULAR_USER         "ppp@a1plus.at"
#define CELLULAR_PASS         "ppp"

// Hardware pin mappings (Waveshare ESP32-S3 A7670E 4G board default mapping)
#define MODEM_UART_TX_PIN     18
#define MODEM_UART_RX_PIN     17
#define MODEM_PWRKEY_PIN      4
#define MODEM_RESET_PIN       5
#define MODEM_UART_BAUDRATE   115200

#define STATUS_LED_PIN        2    // Onboard status indicator LED pin

// PZEM-004T Power Meter — Serial2 UART pins
#define PZEM_UART_RX_PIN      16   // ESP32-S3 GPIO16 → PZEM TX
#define PZEM_UART_TX_PIN      15   // ESP32-S3 GPIO15 → PZEM RX
#define PZEM_MODBUS_ADDR      0xF8 // Default broadcast address

// Default intervals in milliseconds (will be updated dynamically by server config)
#define DEFAULT_REPORT_INTERVAL_MS    30000   // 30 seconds
#define DEFAULT_CONFIG_POLL_MS        300000  // 5 minutes
#define SENSOR_SAMPLING_INTERVAL_MS   5000    // 5 seconds
#define TOKEN_REFRESH_INTERVAL_MS     3000000 // 50 minutes (Firebase token expires in 1 hour)
#define OTA_CHECK_INTERVAL_MS         86400000 // 24 hours

// Edge alerting thresholds (overridden by server configurations)
#define DEFAULT_HIGH_CURRENT_THRESHOLD  18.0
#define DEFAULT_LOW_CURRENT_THRESHOLD   2.0
#define DEFAULT_HIGH_VOLTAGE_THRESHOLD  250.0 // V — overvoltage alert
#define DEFAULT_LOW_VOLTAGE_THRESHOLD   200.0 // V — undervoltage alert
#define ALERT_DEBOUNCE_COUNT            3
#define ALERT_COOLDOWN_MS               300000  // 5 minutes

// Safety Watchdog duration in seconds
#define WATCHDOG_TIMEOUT_SECONDS       120

#endif // CONFIG_H
