#ifndef CONFIG_H
#define CONFIG_H

// Firebase configuration
#define FIREBASE_PROJECT_ID   "pumping-station-iot"
#define FIREBASE_API_KEY      "AIzaSyD-YOUR-REAL-FIREBASE-WEB-API-KEY-HERE"
#define FIREBASE_DB_URL       "https://pumping-station-iot-default-rtdb.europe-west1.firebasedatabase.app"

// Device details (to be replaced with specific station credentials during provisioning)
#define DEFAULT_STATION_ID    "STATION_001"
// Custom provisioning token generated by the server. 
// Devices use this on first boot to establish credentials.
#define DEFAULT_CUSTOM_TOKEN  "PLACE_PROVISIONING_TOKEN_HERE"

// Cellular settings
#define CELLULAR_APN          "iot.1nce.net" // Default 1NCE SIM APN
#define CELLULAR_USER         ""
#define CELLULAR_PASS         ""

// Hardware pin mappings (Waveshare ESP32-S3 A7670E 4G board default mapping)
#define MODEM_UART_TX_PIN     18
#define MODEM_UART_RX_PIN     17
#define MODEM_PWRKEY_PIN      4
#define MODEM_RESET_PIN       5
#define MODEM_UART_BAUDRATE   115200

#define STATUS_LED_PIN        2    // Onboard status indicator LED pin
#define CT_CLAMP_ADC_PIN      1    // GPIO1 (ADC1_CH0) for current reading

// Sensor calibration factors
#define CT_CLAMP_CALIBRATION  20.0 // 20A / 1V output sensor SCT-013-020
#define ADC_VREF              3.3  // ESP32 reference voltage
#define ADC_RESOLUTION        4095.0 // 12-bit ADC
#define BIAS_VOLTAGE          1.65 // Midpoint bias voltage

// Default intervals in milliseconds (will be updated dynamically by server config)
#define DEFAULT_REPORT_INTERVAL_MS    30000   // 30 seconds
#define DEFAULT_CONFIG_POLL_MS        300000  // 5 minutes
#define SENSOR_SAMPLING_INTERVAL_MS   5000    // 5 seconds
#define TOKEN_REFRESH_INTERVAL_MS     3000000 // 50 minutes (Firebase token expires in 1 hour)
#define OTA_CHECK_INTERVAL_MS         86400000 // 24 hours

// Edge alerting thresholds (overridden by server configurations)
#define DEFAULT_HIGH_CURRENT_THRESHOLD 18.0
#define DEFAULT_LOW_CURRENT_THRESHOLD  2.0
#define ALERT_DEBOUNCE_COUNT           3
#define ALERT_COOLDOWN_MS              300000  // 5 minutes

// Safety Watchdog duration in seconds
#define WATCHDOG_TIMEOUT_SECONDS       120

#endif // CONFIG_H
