#ifndef CONFIG_H
#define CONFIG_H

// Firebase configuration
#define FIREBASE_PROJECT_ID "argus360-c0496"
#define FIREBASE_API_KEY "AIzaSyBtGpOwNCicAIl5FUh07nXb39Dh-XPdabE"
#define FIREBASE_DB_URL                                                        \
  "https://argus360-c0496-default-rtdb.europe-west1.firebasedatabase.app"

// Device details (to be replaced with specific station credentials during provisioning)
#define DEFAULT_STATION_ID "STATION_001"
// Custom provisioning token generated by the server.
#define DEFAULT_CUSTOM_TOKEN                                                   \
  "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9."                                      \
  "eyJhdWQiOiJodHRwczovL2lkZW50aXR5dG9vbGtpdC5nb29nbGVhcGlzLmNvbS9nb29nbGUuaW" \
  "RlbnRpdHkuaWRlbnRpdHl0b29sa2l0LnYxLklkZW50aXR5VG9vbGtpdCIsImlhdCI6MTc4Mzky" \
  "ODg3NCwiZXhwIjoxNzgzOTMyNDc0LCJpc3MiOiJhcmd1czM2MC1jMDQ5NkBhcHBzcG90LmdzZX" \
  "J2aWNlYWNjb3VudC5jb20iLCJzdWIiOiJhcmd1czM2MC1jMDQ5NkBhcHBzcG90LmdzZXJ2aWNl" \
  "YWNjb3VudC5jb20iLCJ1aWQiOiJTVEFUSU9OXzAwMSIsImNsYWltcyI6eyJkZXZpY2VUeXBlIj" \
  "oiZXNwMzIiLCJzdGF0aW9uSWQiOiJTVEFUSU9OXzAwMSJ9fQ.GYUT3zudQrh9UDxUcwPOEm3S_" \
  "bQGYo_"                                                                     \
  "qO09LCnXgupdjcjDevexhP8axHPN5DNzwzmOkCBkkgqFGySrrW3gXccX2YtefJGFgCYvBM_"    \
  "oFkRDpTZ6-eFeptASve6GZHtaYhUu54A0KkCL-Ee2iqfOeyCqy_CcZi1DYWhYjD_"           \
  "CqPORWgrYSgDdx2elBFKF3KXhDyqNdRZYfbDeqI1ywGWNgjYd_8R_"                      \
  "TYBbco9FbxCmCvQ0v8B3DU15hSBxq1g9nbuyxKHHJG4yRy0uP2KSA9kU0Rk2UZSJtwJEt7-"    \
  "lno9qBxCXUBJ6Seha55t5AHV5mSlKrXnjtOdU_POKucfPuKbixeQ"

// Cellular settings
#define CELLULAR_APN "a1.net"
#define CELLULAR_USER "ppp@a1plus.at"
#define CELLULAR_PASS "ppp"

// Hardware pin mappings (Waveshare ESP32-S3 A7670E 4G-EN board mapping)
#define MODEM_UART_TX_PIN 18
#define MODEM_UART_RX_PIN 17
#define MODEM_PWRKEY_PIN 4
#define MODEM_RESET_PIN 33
#define MODEM_FLIGHT_PIN 25
#define MODEM_UART_BAUDRATE 115200

#define STATUS_LED_PIN 21

// MAX17048 battery gauge
#define BATTERY_GAUGE_I2C_ADDR 0x36

// Modem watchdog / recovery timing
#define MODEM_FAILS_BEFORE_SOFT_RESET 5
#define MODEM_SOFT_RESET_RECOVERY_WAIT_MS 15000
#define MODEM_WATCHDOG_INTERVAL_MS 1000

// PZEM-004T Power Meter — Serial2 UART pins
#define PZEM_UART_RX_PIN 16
#define PZEM_UART_TX_PIN 15
#define PZEM_MODBUS_ADDR 0xF8

// Default intervals in milliseconds
#define DEFAULT_REPORT_INTERVAL_MS 30000
#define DEFAULT_CONFIG_POLL_MS 300000
#define SENSOR_SAMPLING_INTERVAL_MS 5000
#define OTA_CHECK_INTERVAL_MS 86400000

// Edge alerting thresholds
#define DEFAULT_HIGH_CURRENT_THRESHOLD 18.0
#define DEFAULT_LOW_CURRENT_THRESHOLD 2.0
#define DEFAULT_HIGH_VOLTAGE_THRESHOLD 250.0
#define DEFAULT_LOW_VOLTAGE_THRESHOLD 200.0
#define ALERT_DEBOUNCE_COUNT 3
#define ALERT_COOLDOWN_MS 300000

// Safety Watchdog duration in seconds
#define WATCHDOG_TIMEOUT_SECONDS 120

#endif // CONFIG_H
