[env:waveshare_esp32s3_a7670e]
platform      = espressif32
board         = esp32-s3-devkitc-1
framework     = arduino

board_build.mcu           = esp32s3
board_build.f_cpu         = 240000000L
board_upload.flash_size   = 16MB
board_build.partitions    = default_8MB.csv

monitor_speed  = 115200
monitor_filters = esp32_exception_decoder

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=3
    -mfix-esp32-psram-cache-issue
    '-DFIREBASE_WEB_API_KEY="AIzaSyBtGpOwNCicAIl5FUh07nXb39Dh-XPdabE"'

lib_deps =
    mandulaj/PZEM-004T-v30 @ ^1.1.2
    adafruit/Adafruit NeoPixel @ ^1.12.3
    adafruit/Adafruit MAX1704X @ ^1.0.3
    bblanchon/ArduinoJson @ ^7.0.0
